version: '3'
services:
  assess3_seconion_api:
    container_name: assess3_seconion_api
    build: 
      context: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "9000:3000"
    volumes: 
      - ./src:/usr/app-api
